# Generated by Django 6.0.2 on 2026-05-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_cpf_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
