# Generated by Django 6.0.2 on 2026-06-10 01:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_name_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAddress",
        ),
    ]
