# Generated by Django 6.0.2 on 2026-07-09 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogOutbox',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Outbox',
                'verbose_name_plural': 'Log Outbox',
                'db_table': 'log_outbox',
                'ordering': ['created_at'],
            },
        ),
    ]
