# Generated by Django 6.0.2 on 2026-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoutbox',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
